language: r
sudo: true
cache: packages

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true

apt_packages:
  - libudunits2-dev
warnings_are_errors: false
